'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Klienti
    Public Property ID_Klienta As String
    Public Property FIO As String
    Public Property LOGIN As String
    Public Property EMAIL As String
    Public Property PAROL_ As String
    Public Property Autentifikacionnii_klych As String

    Public Overridable Property Trenirovka As ICollection(Of Trenirovka) = New HashSet(Of Trenirovka)

End Class
