'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Kompleksi
    Public Property ID_Kompleksa As String
    Public Property Razpolojenie As String
    Public Property Kolichestvo As String

    Public Overridable Property Administrator As ICollection(Of Administrator) = New HashSet(Of Administrator)
    Public Overridable Property Trenirovka As ICollection(Of Trenirovka) = New HashSet(Of Trenirovka)

End Class
