'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Sportivnii_kompleksEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Sportivnii_kompleksEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Administrator() As DbSet(Of Administrator)
    Public Overridable Property Klienti() As DbSet(Of Klienti)
    Public Overridable Property Kompleksi() As DbSet(Of Kompleksi)
    Public Overridable Property Moderator() As DbSet(Of Moderator)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property Trener() As DbSet(Of Trener)
    Public Overridable Property Trenirovka() As DbSet(Of Trenirovka)
    Public Overridable Property Zali() As DbSet(Of Zali)
    Public Overridable Property Zapis__na_trenirovku() As DbSet(Of Zapis__na_trenirovku)

End Class
