'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Moderator
    Public Property ID_Moderator As String
    Public Property ID_Trenirovka As String
    Public Property FIO As String
    Public Property EMAIL As String

    Public Overridable Property Trenirovka As Trenirovka
    Public Overridable Property Trenirovka1 As ICollection(Of Trenirovka) = New HashSet(Of Trenirovka)
    Public Overridable Property Zali As ICollection(Of Zali) = New HashSet(Of Zali)

End Class
