'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Trener
    Public Property ID_Trener As String
    Public Property FIO As String
    Public Property EMAIL As String

    Public Overridable Property Zapis__na_trenirovku As ICollection(Of Zapis__na_trenirovku) = New HashSet(Of Zapis__na_trenirovku)

End Class
