'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Zali
    Public Property ID_Zala As String
    Public Property ID_Administrator As String
    Public Property ID_Moderator As String
    Public Property Opisanie As String

    Public Overridable Property Administrator As ICollection(Of Administrator) = New HashSet(Of Administrator)
    Public Overridable Property Administrator1 As Administrator
    Public Overridable Property Moderator As Moderator
    Public Overridable Property Trenirovka As ICollection(Of Trenirovka) = New HashSet(Of Trenirovka)

End Class
